# Generated by Django 5.2.6 on 2025-10-16 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_borrowrecord_student_id_alter_borrowrecord_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinevent',
            name='staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkinevent',
            name='students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='checkinevent',
            index=models.Index(fields=['facility', 'occurred_at'], name='core_checki_facilit_d95bcb_idx'),
        ),
    ]
